#!/usr/bin/env node
/**
 * Regenerates ENVIRONMENTS.md with the current live deployment status.
 *
 * The STABLE URLs (dev alias + prod domain) never change — bookmark those.
 * This script additionally records the latest underlying deployment (the
 * per-deploy URL, its state, and the commit) so you can see what's live.
 *
 * Usage:  npm run urls
 * Reads VERCEL_TOKEN / VERCEL_ORG_ID / VERCEL_PROJECT_ID from .env.local
 * (falls back to process.env).
 *
 * @module scripts/update-urls
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { resolve } from 'node:path'

// ── Stable, never-changing entry points ───────────────────────────────────
const DEV = { alias: 'https://reserve-it-dev.vercel.app', db: 'nqoloqrldqgrbeeujkdw' }
const PROD = { alias: 'https://reserve-it-six.vercel.app', db: 'aascxdiyetopvrxifape' }

// ── Read creds from .env.local (or process.env) ───────────────────────────
function loadEnv() {
  const env = { ...process.env }
  const path = resolve(process.cwd(), '.env.local')
  if (existsSync(path)) {
    for (const line of readFileSync(path, 'utf8').split('\n')) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/)
      if (m && !env[m[1]]) env[m[1]] = m[2].replace(/^["']|["']$/g, '')
    }
  }
  return env
}

const env = loadEnv()
const TOKEN = env.VERCEL_TOKEN
const TEAM = env.VERCEL_ORG_ID
const PROJECT = env.VERCEL_PROJECT_ID

async function latestDeployment({ target, branch }) {
  if (!TOKEN || !TEAM || !PROJECT) return null
  const url = new URL('https://api.vercel.com/v6/deployments')
  url.searchParams.set('projectId', PROJECT)
  url.searchParams.set('teamId', TEAM)
  url.searchParams.set('limit', '20')
  if (target) url.searchParams.set('target', target)
  const res = await fetch(url, { headers: { Authorization: `Bearer ${TOKEN}` } })
  if (!res.ok) return null
  const { deployments = [] } = await res.json()
  const match = deployments.find(
    (d) => (!branch || d.meta?.githubCommitRef === branch) && d.state === 'READY'
  ) || deployments[0]
  if (!match) return null
  return {
    url: `https://${match.url}`,
    state: match.state,
    branch: match.meta?.githubCommitRef ?? '—',
    sha: (match.meta?.githubCommitSha ?? '').slice(0, 7) || '—',
    when: new Date(match.created).toISOString().replace('T', ' ').slice(0, 16) + ' UTC',
  }
}

function row(d) {
  return d
    ? `${d.url} · **${d.state}** · \`${d.branch}@${d.sha}\` · ${d.when}`
    : '_run `npm run urls` with VERCEL_TOKEN set to populate_'
}

const [devDep, prodDep] = await Promise.all([
  latestDeployment({ target: 'preview', branch: 'dev' }),
  latestDeployment({ target: 'production', branch: 'main' }),
])

const stamp = new Date().toISOString().replace('T', ' ').slice(0, 16) + ' UTC'

const md = `# Environments

> Auto-generated by \`npm run urls\` — last refreshed **${stamp}**.
> The **Stable URL** column is permanent. Bookmark those; they always point at the
> newest successful deploy. The per-deploy URLs below them change every deploy.

| Environment | Stable URL (bookmark this) | Database | Branch |
|-------------|----------------------------|----------|--------|
| 🟢 **Production** | ${PROD.alias} | \`${PROD.db}\` | \`main\` |
| 🔵 **Dev / Staging** | ${DEV.alias} | \`${DEV.db}\` | \`dev\` |
| 💻 **Local** | http://localhost:3000 | Docker (\`npm run db:local:start\`) | \`feature/*\` |

## Latest underlying deployments

- **Production:** ${row(prodDep)}
- **Dev:** ${row(devDep)}

## How it stays current

- **Prod** — Vercel auto-points \`reserve-it-six.vercel.app\` to the latest \`main\` deploy.
- **Dev** — \`deploy-dev.yml\` re-aliases \`reserve-it-dev.vercel.app\` to each new \`dev\` deploy.
- Refresh the snapshot above any time with \`npm run urls\`.
`

writeFileSync(resolve(process.cwd(), 'ENVIRONMENTS.md'), md)
console.log('ENVIRONMENTS.md updated.')
console.log(`  Prod: ${PROD.alias}  ->  ${prodDep?.url ?? '(unknown)'} [${prodDep?.state ?? '?'}]`)
console.log(`  Dev:  ${DEV.alias}  ->  ${devDep?.url ?? '(unknown)'} [${devDep?.state ?? '?'}]`)
